tbUse('ECoG_utils');

% SCRIPT DESCRIPTION %
% Takes BAIR data from NYU School of Medicine, gets onsets, writes out
% separate runs for each tasks, including tsv event files, and required
% BIDS metadata (coordsystem json and electrodes and channels tsv files). 
%
% Remarks:
% - Data is written in BVA format (.eeg, .vhdr, .vmrk), because of a bug
% with EDF writing, but this can be changed (see line 295). Can also decide
% to zip the BVA files for Flywheel (currently turned off).
% - Should we put the original data in /sourcedata/ folder? (may depend on
% whether data is sufficiently anonymized)
% - Should there be a json sidecar with the T1 file?

%% Define paths and BIDS specs %%

% Input paths specs
patientID   = 692;
RawDataDir  = '/Volumes/server/Projects/BAIR/Data/Raw/ECoG/';
BIDSDataDir = '/Volumes/server/Projects/BAIR/Data/BIDS/';

% BIDS specs
projectName = 'visual';
sub_label   = ['som' num2str(patientID)]; 
ses_label   = 'nyuecog01';
ses_labelt1 = 'som3t01';
task_label  = {'prf',...
               'prf', ...
               'spatialpattern', ...
               'spatialpattern', ...
               'spatialobject', ...
               'spatialobject', ...
               'temporalpattern', ...            
               'temporalpattern', ... 
               'spatialpattern', ...
               'spatialpattern', ...
               'spatialobject', ...
               'spatialobject', ...
               'temporalpattern', ...            
               'temporalpattern', ...
              };              
run_label = {'01','02','01','02','01','02','01','02','03','04','03','04','03','04'};

% Output paths specs
dataWriteDir = fullfile(BIDSDataDir, projectName, sprintf('sub-%s', sub_label), sprintf('ses-%s', ses_label), 'ieeg');
stimWriteDir = fullfile(BIDSDataDir, projectName, 'stimuli');
T1WriteDir   = fullfile(BIDSDataDir, projectName, sprintf('sub-%s', sub_label), sprintf('ses-%s', ses_labelt1), 'anat');

% Define temporal parameters
% --> These data have task onset and offset triggers.
prescan   = 0; % Segment each run with this amount before the first stimulus onset (seconds)
postscan  = 0; % Segment each run with this amount after the last stimulus onset (seconds)
nDecimals = 6; % Specify temporal precision of time stamps in events files

% Make plots?
makePlots = 'no';

%% Create write directories

if ~exist(dataWriteDir, 'dir'); mkdir(dataWriteDir);end
if ~exist(T1WriteDir, 'dir'); mkdir(T1WriteDir);end

%% READ IN relevant data files %%%%%%%%%%%%%%%%%%

%   - ECoG data file
%   - electrode coordinate file provided by SoM
%   - stimulus log files generated by stimulus code

%% Read in ECoG data

% Read ECoG data
dataFiles = dir(fullfile(RawDataDir,num2str(patientID), '*.edf'));
if length(dataFiles) > 1, disp('warning: multiple datafiles found: using first one'); end

fileName = [dataFiles(1).folder filesep dataFiles(1).name];    
disp(['reading ' fileName '...']);
hdr = ft_read_header(fileName);
data = ft_read_data(fileName);
% To read in EDF data with channels with different sampling rates: data = edf2fieldtrip(fileName);

%% MANUAL STEP:  Inspect the time course of each of the channels 

% Write down the trigger channel (probably one labeled 'DC', see hdr.label)
% Write down bad channels (e.g. those with big spikes)
t = ((1:hdr.nSamples)/hdr.Fs); % time in seconds
switch makePlots 
    case 'yes'
        for cChan = size(data,1):-1:1; figure;plot(t,data(cChan,:)); title([num2str(cChan) ': ' hdr.label{cChan}]);waitforbuttonpress; close; end
end

% Specify the trigger channel
triggerChannel = 153; % DC1
badChannels = [33 48 89 93 94 96 112 124 127:150];
badChannelsDescriptions = repmat({'spikes'}, 1,length(badChannels)); % use this to indicate the reason why channels were marked as bad

%% MANUAL STEP: Check channel selection

% Specify the ecog channels (look at hdr.label to guess from the channel
% names, or by looking at the time courses at previous step)
seegChannels = 1:150;

% Generate spectral plot; check command window output for outliers; 
% Are they all in the list of badChannels?
switch makePlots 
    case 'yes'
        [outliers] = ecog_plotChannelSpectra(data, seegChannels, hdr);
end

% NOTE: outliers (identified as channels with mean power that is more that
% two standard deviations above or below the average across channels should
% not be used to automatically identify bad channels, because channels with
% strong activation can have higher power on average! Instead, look at
% the time courses of those channels again

switch makePlots 
    case 'yes'
        for cChan = 1:length(outliers);figure; plot(t, data(outliers(cChan),:)); title([num2str(outliers(cChan)) ': ' hdr.label{outliers(cChan)}]); waitforbuttonpress; close; end
end

goodChannels = setdiff(find(seegChannels),badChannels);

switch makePlots 
    case 'yes'
        % Check the powerplot of all the good channels, no leftover outliers?
        ecog_plotChannelSpectra(data, goodChannels, hdr)

        % Check the timeseries of all the good channels, no noisy moments?
        figure;plot(t,data(goodChannels,:)); xlabel('Time (s)'); ylabel('Amplitude'); set(gca,'fontsize',16);
end

%% Get trigger time points from data file
triggers = data(triggerChannel,:);
triggers = triggers / max(triggers);

disp('Reading triggers from data');
[~,trigger_onsets] = findpeaks(triggers, hdr.Fs, 'MinPeakHeight', 0.8, 'MinPeakDistance', .5);

switch makePlots 
    case 'yes'
        figure;hold on
        plot(t,data(triggerChannel,:))
        stem(trigger_onsets,ones(length(trigger_onsets),1)*(max(data(triggerChannel,:))/2),'r');
        legend({'trigger data', 'trigger onsets'}); xlabel('time (s)'); ylabel('amplitude');
end

%% Read in stimulus files

stimDir = fullfile(RawDataDir,num2str(patientID), 'stimdata');
stimMatFiles = dir(fullfile(stimDir, sprintf('sub-%d*.mat', patientID)));
stimTSVFiles = dir(fullfile(stimDir, sprintf('sub-%d*.tsv', patientID)));

% CHECK: Do we have all the stimfiles?
disp('Checking whether have all the stimFiles')
assert(isequal(length(stimMatFiles), length(run_label)))
assert(isequal(length(stimTSVFiles), length(run_label)))
nRuns = length(run_label);

% NOTE: It's important to read the StimFiles in in the correct order.
% Because the logfiles are copied over, we can't assume that
% stimFiles(ii).date is correct. Instead, we sort them based on the field
% "experimentDateandTime" in params saved out by the stimulus code.

% Read the stimfiles
clear stimData;
runTimes = [];
for ii = 1:length(stimMatFiles)
    stimData(ii) = load([stimDir filesep stimMatFiles(ii).name]);
    disp(['Reading ' stimData(ii).fname])
    runTimes{ii} = stimData(ii).params.experimentDateandTime;
    switch makePlots 
        case 'yes'
            figure(ii); clf
            plot(stimData(ii).stimulus.seqtiming, stimData(ii).stimulus.trigSeq, 'o-')
    end
end

% Sort the stimfiles, count how many triggers were requested
[sortedRunTimes, runIndex] = sort(runTimes);
disp('Sorting runs in recorded order. New run order is: ')
stimData_sorted = stimData(runIndex);
requestedTriggerCount = 0;
for ii = 1:length(stimMatFiles)
    disp([stimData_sorted(ii).fname])
    num_triggers = length(find(stimData_sorted(ii).stimulus.trigSeq));
    requestedTriggerCount = requestedTriggerCount+num_triggers;
end

% CHECK: Does the number of requested triggers match the number of triggers
% that were detected in the trigger channel?
disp('Checking whether all triggers are in the data')
assert(isequal(requestedTriggerCount, length(trigger_onsets)))

%read in tsv files later to replace onset with segmented trigger onsets
%readtable([stimDir filesep stimTSVFiles(ii).name], 'FileType');

%% Read in electrode information

% Locate and read the electrode file provided by SOM
% We want the one that matches the T1
ElecFile = dir(fullfile(RawDataDir,num2str(patientID),'*coor_T1*.txt'));
if length(ElecFile) > 1, disp('warning: multiple elec files found: using first one'); end
if length(ElecFile) < 1
    disp('warning: no coordinate file found!') 
else
    disp(['Reading electrode information from: ' ElecFile.name]); % if there are multiple coor_T1 files for separate hemispheres, D(1) will always be the full list
    elec_fname = fullfile(ElecFile.folder,ElecFile.name);
    fid = fopen(elec_fname); E = textscan(fid, '%s%f%f%f%s'); fclose(fid);
    elec_xyz = [E{2} E{3} E{4}]; 
    elec_labels = E{1};
    elec_types = E{5};
    disp(['Types of electrodes found: ' unique(strcat(elec_types{:}))]);
    % Replace elec_types with BIDS terminology
    elec_types = replace(elec_types, 'G', 'surface');
    elec_types = replace(elec_types, 'D', 'depth');
    elec_types = replace(elec_types, 'S', 'surface');
end

% Match elec names; sort coordinates and electrode types based on matching
[elecInx, chanNames, chanTypes, chanUnits] = getChannelSpecs(hdr, elec_labels);

% Generate a channel table default (written out for each run in big loop below)
[channel_table] = createBIDS_ieeg_channels_tsv_nyuSOM(length(chanNames));
channel_table.name  = chanNames;
channel_table.type  = chanTypes;
channel_table.units = chanUnits;
channel_table.sampling_frequency = repmat(hdr.Fs,size(channel_table,1),1);

% Indicate which channel is the trigger channel in channels.tsv
channel_table.type{triggerChannel} = 'trig';

% Indicate channel statuses
channel_table.status = cell(height(channel_table),1);
channel_table.status_description = cell(height(channel_table),1);
seegChannels = find(contains(channel_table.type,'seeg'));
for ii = 1:length(seegChannels)
    channel_table.status{seegChannels(ii)} = 'good';
end
for ii = 1:length(badChannels)
    channel_table.status{badChannels(ii)} = 'bad';
    if exist('badChannelsDescriptions', 'var')
        channel_table.status_description{badChannels(ii)} = badChannelsDescriptions{ii};
    end
end

%% START OF WRITING FILES %%

%% Create DATASET-SPECIFIC files %%%%%%%%%%%%%%%%%%

%   - T1w.nii.gz
%   - coordsystem.json
%   - electrodes.tsv

%% Create T1w file

% Locate T1 provided by SoM
T1File = dir(fullfile(RawDataDir,num2str(patientID), 'T1.nii.gz'));
if length(T1File) > 1, disp('warning: multiple T1s found: using first one'); end

% Copy file: rename and save in appropriate folder
if length(T1File) < 1
    disp('warning: no T1 found!') 
else
    T1_name = fullfile(T1WriteDir, sprintf('sub-%s_ses-%s_T1w.nii.gz', sub_label, ses_labelt1));
    disp(['Writing ' T1_name '...']);
    copyfile(fullfile(RawDataDir,num2str(patientID), 'T1.nii.gz'), T1_name);
end

% Note on pial file: surface recons should go in derivatives folder (see
% BIDS spec doc). If we want to include this in our data do we use our own
% freesurfer recon (which we use for electrode plotting) or the one
% provided by SOM (but why is that a .mat file)? If so, we should probably
% also provide an electrode locations file based on matched nodes
% (see run_E2N and electrode_to_nearest_node scripts in ECoG_utils)

%% Create coordsystem.json file

% Generate output name
coord_json_name = fullfile(dataWriteDir, sprintf('sub-%s_ses-%s_coordsystem.json', sub_label, ses_label));

% Get default values
[coordsystem_json, json_options] = createBIDS_ieeg_coordsystem_json_nyuSOM();

% Update values with specs for this subject
coordsystem_json.IntendedFor = fullfile(sprintf('sub-%s', sub_label), sprintf('ses-%s', ses_labelt1), 'anat', ...
    sprintf('sub-%s_ses-%s_T1w.nii.gz', sub_label, ses_labelt1)); % this path must be specified relative to the project folder

% Write coordsystem.json file
disp(['Writing ' coord_json_name '...']);
jsonwrite(coord_json_name,coordsystem_json,json_options);

% Note on coordystem json file: SOM also provides electrode locations in
% MNI space, as well as a list of matched anatomical regions. Do we want to
% include this information in our BIDS dataset as well? The MNI coordinates
% could be included as another coordsystem file (and associated
% electrodes.tsv file) which can be distinguished from the T1 coordinates
% by adding a [_space-<label>] to the filenames (see BIDS iEEG section
% 3.4.1). SOM does not provide an MNI aligned T1 to go along with this file
% however (unless that is the *_elec_T1.nii.gz file that they include?).

%% Create electrodes.tsv file

% Generate table with SOM defaults
n = length(elecInx);
[electrode_table] = createBIDS_ieeg_electrodes_tsv_nyuSOM(n);

% Fill with relevant information:
electrode_table.name = elec_labels(elecInx);
electrode_table.x = elec_xyz(elecInx,1);
electrode_table.y = elec_xyz(elecInx,2);
electrode_table.z = elec_xyz(elecInx,3);
electrode_table.type = elec_types(elecInx);

% Generate output name
electrodes_tsv_name = fullfile(dataWriteDir, sprintf('sub-%s_ses-%s_electrodes.tsv', sub_label, ses_label));

% Write tsv file
disp(['Writing ' electrodes_tsv_name '...']);
writetable(electrode_table,electrodes_tsv_name,'FileType','text','Delimiter','\t');

%% Create RUN-SPECIFIC files %%%%%%%%%%%%%%%%%%

% It generates:
%   - events.tsv
%   - ieeg.edf 
%   - .mat with stimulus info per run (goes in main 'stimuli' folder)
%   - ieeg.json 
%   - channels.tsv

%% Big loop across runs

% This loop:
%   - extracts run-specific stimulus information from stimulus files
%   - matches stimuli to trigger onsets
%   - splits data up in separate runs
%   - writes out all the run specific files required for BIDS

num_triggers_total = 0;

for ii = 1:nRuns
    
    stim0 = num_triggers_total+1;
    
    % Generate filename
    fname = sprintf('sub-%s_ses-%s_task-%s_run-%s', ...
            sub_label, ses_label, task_label{ii}, run_label{ii});
    fprintf('Writing eeg, events, stimuli, json and channel files for %s \n', fname);
    
    % Generate a json file default
    [ieeg_json, json_options] = createBIDS_ieeg_json_nyuSOM();
    
    % Collect info for json file   
    if contains(task_label{ii}, 'hrf')                 
        ieeg_json.TaskName = 'bair_hrfpattern';
        ieeg_json.TaskDescription = 'Visual textures presented at irregular intervals';        
    elseif contains(task_label{ii}, 'prf')         
        ieeg_json.TaskName = 'bair_prf';
        ieeg_json.TaskDescription = 'Visual bar apertures of textures sweeping across screen';	
    elseif contains(task_label{ii}, 'spatialpattern')        
        ieeg_json.TaskName = 'bair_spatialpattern';
        ieeg_json.TaskDescription = 'Visual textures and gratings presented for brief, fixed durations';    
    elseif contains(task_label{ii}, 'temporalpattern') 
        ieeg_json.TaskName = 'bair_temporalpattern';
        ieeg_json.TaskDescription = 'Visual textures presented for variable durations and inter-stimulus intervals';      
	elseif contains(task_label{ii}, 'spatialobject')       
        ieeg_json.TaskName = 'bair_spatialobject';
        ieeg_json.TaskDescription = 'Houses faces and letter images presented brief, fixed durations';         
    end   
    ieeg_json.Instructions = 'Detect color change (red/green) at fixation';
    
    % Get the onsets for this run
    num_triggers = length(find(stimData_sorted(ii).stimulus.trigSeq));
    num_triggers_total = num_triggers_total + num_triggers;
    onsets = trigger_onsets(stim0:num_triggers_total); 
    [~,onset_indices] = intersect(t, onsets);

    % First trigger is task onset trigger:
    run_start_inx = onset_indices(1);
    % Last trigger is task offset trigger:
    run_stop_inx = onset_indices(end);
    % Stimulus onsets are those in between
    onsets = onsets(2:end-1); 
    onset_indices = onset_indices(2:end-1);

    % Clip data from run using task onset and offset triggers
    data_thisrun = data(:,run_start_inx:run_stop_inx-1); % subtract one sample to make length of 'between run' data exactly 6 seconds
    hdr_thisrun = hdr;
    hdr_thisrun.nSamples = size(data_thisrun,2);

    % Write out new data file
     
    % Use BVA format
    data_fname = fullfile(dataWriteDir, sprintf('%s_ieeg', fname));
    ft_write_data(data_fname, data_thisrun, 'header', hdr_thisrun, 'dataformat', 'brainvision_eeg');
    
    % % May need to zip files for Flywheel upload?
    %zip(data_fname, {sprintf('%s.eeg', data_fname), sprintf('%s.vhdr', data_fname), sprintf('%s.vmrk', data_fname)});
    %delete(sprintf('%s.eeg', data_fname), sprintf('%s.vhdr', data_fname), sprintf('%s.vmrk', data_fname));
    
    % Collect info for tsv file
    events_table = stimData(ii).stimulus.tsv;
    
    % Overwrite onset with onsets of triggers
    %events_table.onset       = round(onsets'-onsets(1)+prescan,nDecimals);
    events_table.onset_index = (onset_indices - run_start_inx);
    events_table.onset       = round(events_table.onset_index/hdr.Fs,nDecimals);
    events_table.stim_file   = repmat(fname, height(events_table), 1);

    % Write out tsv file 
    tsv_thisrun = events_table;
    tsv_fname = fullfile(dataWriteDir, sprintf('%s_events.tsv', fname));
    writetable(tsv_thisrun, tsv_fname, 'FileType','text', 'Delimiter', '\t')
    
    % Write out stimulus file
    stimfile_thisrun = stimData(ii);
    stimfile_fname = fullfile(stimWriteDir, sprintf('%s.mat', fname));
    save(stimfile_fname, '-struct', 'stimfile_thisrun', '-v7.3')
    
    % Collect info for json_ieeg file
    ieeg_json.SamplingFrequency = hdr_thisrun.Fs;
    ieeg_json.RecordingDuration = round(hdr_thisrun.nSamples/hdr_thisrun.Fs,nDecimals);
    
    % Write out json_ieeg file
    jsonfile_fname = fullfile(dataWriteDir, sprintf('%s_ieeg.json', fname));    
    jsonwrite(jsonfile_fname,ieeg_json,json_options)
    
    % Write out channels.tsv file
    channels_tsv_fname = fullfile(dataWriteDir, sprintf('%s_channels.tsv', fname));    
    writetable(channel_table,channels_tsv_fname,'FileType','text','Delimiter','\t');
    
    % CHECK: Are the onsets from the stimulus file and triggers aligned?
    switch makePlots 
        case 'yes'
            figure; hold on;
            stem(onsets-onsets(1)); 
            stem(stimData(ii).stimulus.onsets - stimData(ii).stimulus.onsets(1), ':diamondr')
            xlabel('Event number'); ylabel('Time (s)');
            legend('Triggers', 'Stimulus Onsets')
    end

end

% CHECK: Do number of triggers derived from EDF data file match the number
% of trials from the stimulus files?
assert(isequal(length(trigger_onsets), num_triggers_total))
disp('done');


