tbUse('ECoG_utils');

% SCRIPT DESCRIPTION %
% Takes BAIR data from NYU School of Medicine, gets onsets, writes out
% separate runs for each tasks, including tsv event files, and required
% BIDS metadata (coordsystem json and electrodes and channels tsv files). 

%% Define paths and BIDS specs %%

% Input paths specs
patientID   = 648;
RawDataDir  = '/Volumes/server/Projects/BAIR/Data/Raw/ECoG/';
BIDSDataDir = '/Volumes/server/Projects/BAIR/Data/BIDS/';

% BIDS specs
projectName = 'visual';
sub_label   = 'som648'; 
ses_label   = 'nyuecog01';
ses_labelt1 = 'som3t01';
task_label  = {'hrfpattern',...
              'soc', ...
              'soc', ...
              'soc', ...
              'soc', ...
              'soc', ...
              'soc', ...            
              'soc', ...
              'soc', ... 
              'soc', ...              
              'soc', ...              
              'soc', ...              
              'soc', ...
              'hrfpattern'};              
run_label = {'01','01','02', '03','04', '05','06', '07','08', '09', '10','11','12', '02'};

% Output paths specs
dataWriteDir = fullfile(BIDSDataDir, projectName, sprintf('sub-%s', sub_label), sprintf('ses-%s', ses_label), 'ieeg');
stimWriteDir = fullfile(BIDSDataDir, projectName, 'stimuli');
T1WriteDir   = fullfile(BIDSDataDir, projectName, sprintf('sub-%s', sub_label), sprintf('ses-%s', ses_labelt1), 'anat');

% Define run pre and post baseline periods
prescan  = 3; % seconds
postscan = 3; % seconds

%% READ IN relevant data files %%%%%%%%%%%%%%%%%%

%   - ECoG data file
%   - electrode coordinate file provided by SoM
%   - stimulus log files generated by stimulus code

%% Read in ECoG data

% Read ECoG data
dataFiles = dir(fullfile(RawDataDir,num2str(patientID), '*.edf'));
if length(dataFiles) > 1, disp('warning: multiple datafiles found: using first one'); end

fileName = [dataFiles(1).folder filesep dataFiles(1).name];    
data = ft_read_data(fileName);
hdr = ft_read_header(fileName);
% To read in EDF data with channels with different sampling rates: data = edf2fieldtrip(fileName);

% Identify trigger channel and task indices
% for cChan = size(data,1):-1:1; figure;plot(data(cChan,:)); title([num2str(cChan) ': ' hdr.label{cChan}]);waitforbuttonpress;close; end

% Get trigger time points from data file
triggerChannel = 138; % DC10 

triggers = data(triggerChannel,:);
triggers = triggers / max(triggers);
[~,trigger_onsets] = findpeaks(triggers, hdr.Fs, 'MinPeakHeight', 0.8, 'MinPeakDistance', .5);
t = ((1:hdr.nSamples)/hdr.Fs); % time in seconds

%% Read in electrode information

% Locate and read the electrode file provided by SOM
% We want the one that matches the T1
ElecFile = dir(fullfile(RawDataDir,num2str(patientID),'*coor_T1*.txt'));
if length(ElecFile) > 1, disp('warning: multiple elec files found: using first one'); end
if length(ElecFile) < 1
    disp('warning: no coordinate file found!') 
else
    disp(['reading ' ElecFile.name]); % if there are multiple coor_T1 files for separate hemispheres, D(1) will always be the full list
    elec_fname = fullfile(ElecFile.folder,ElecFile.name);
    fid = fopen(elec_fname); E = textscan(fid, '%s%f%f%f%s'); fclose(fid);
    elec_xyz = [E{2} E{3} E{4}]; 
    elec_labels = E{1};
    elec_types = E{5};
    disp(['types of electrodes found: ' unique(strcat(elec_types{:}))]);
    % Replace elec_types with BIDS terminology
    elec_types = replace(elec_types, 'G', 'surface');
    elec_types = replace(elec_types, 'D', 'depth');
    elec_types = replace(elec_types, 'S', 'surface');
end

% Match elec names; sort coordinates and electrode types based on matching
[elecInx, chanNames, chanTypes, chanUnits] = getChannelSpecs(hdr, elec_labels);

% Generate a channel table default (written out for each run in big loop below)
[channel_table] = createBIDS_ieeg_channels_tsv_nyuSOM(length(chanNames));
channel_table.name  = chanNames;
channel_table.type  = chanTypes;
channel_table.units = chanUnits;
channel_table.sampling_frequency = repmat(hdr.Fs,size(channel_table,1),1);
channel_table.type{triggerChannel} = 'trig';

%% Read in stimulus files

stimDir = fullfile(RawDataDir,num2str(patientID), 'stimdata');
stimFiles = dir(fullfile(stimDir, sprintf('%s*2017*.mat', num2str(patientID))));

for ii = 1:length(stimFiles)
    fileName = [stimDir filesep stimFiles(ii).name];
    stimData(ii) = load(fileName) ;    
    disp(stimData(ii).params.loadMatrix)
    %figure(ii); clf
    %plot(stimData(ii).stimulus.seqtiming, stimData(ii).stimulus.seq, 'o-')
end

% CHECK: Do we have all the stimfiles?
assert(isequal(length(stimData), length(run_label)))

%% Create DATASET-SPECIFIC files %%%%%%%%%%%%%%%%%%

%   - T1w.nii.gz
%   - coordsystem.json
%   - electrodes.tsv

%% Create T1w file

% Locate T1 provided by SoM
T1File = dir(fullfile(RawDataDir,num2str(patientID), 'T1.nii.gz'));
if length(T1File) > 1, disp('warning: multiple T1s found: using first one'); end

% Copy file: rename and save in appropriate folder
if length(T1File) < 1
    disp('warning: no T1 found!') 
else
    T1_name = fullfile(T1WriteDir, sprintf('sub-%s_ses-%s_T1w.nii.gz', sub_label, ses_labelt1));
    [SUCCESS,MESSAGE,MESSAGEID] = copyfile(fullfile(RawDataDir,num2str(patientID), 'T1.nii.gz'), T1_name);
end

% Note on pial file: surface recons should go in derivatives folder (see
% BIDS spec doc). If we want to include this in our data do we use our own
% freesurfer recon (which we use for electrode plotting) or the one
% provided by SOM (but why is that a .mat file)? If so, we should probably
% also provide an electrode locations file based on matched nodes
% (see run_E2N and electrode_to_nearest_node scripts in ECoG_utils)

%% Create coordsystem.json file

% Generate output name
coord_json_name = fullfile(dataWriteDir, sprintf('sub-%s_ses-%s_coordsystem.json', sub_label, ses_label));

% Get default values
[coordsystem_json, json_options] = createBIDS_ieeg_coordsystem_json_nyuSOM();

% Update values with specs for this subject
coordsystem_json.IntendedFor = fullfile(sprintf('sub-%s', sub_label), sprintf('ses-%s', ses_labelt1), 'anat', ...
    sprintf('sub-%s_ses-%s_T1w.nii.gz', sub_label, ses_labelt1)); % this path must be specified relative to the project folder

% Write coordsystem.json file
jsonwrite(coord_json_name,coordsystem_json,json_options);

% Note on coordystem json file: SOM also provides electrode locations in
% MNI space, as well as a list of matched anatomical regions. Do we want to
% include this information in our BIDS dataset as well? The MNI coordinates
% could be included as another coordsystem file (and associated
% electrodes.tsv file) which can be distinguished from the T1 coordinates
% by adding a [_space-<label>] to the filenames (see BIDS iEEG section
% 3.4.1). SOM does not provide an MNI aligned T1 to go along with this file
% however (unless that is the *_elec_T1.nii.gz file that they include?).

%% Create electrodes.tsv file

% Generate table with SOM defaults
n = length(elecInx);
[electrode_table] = createBIDS_ieeg_electrodes_tsv_nyuSOM(n);

% Fill with relevant information:
electrode_table.name = elec_labels(elecInx);
electrode_table.x = elec_xyz(elecInx,1);
electrode_table.y = elec_xyz(elecInx,2);
electrode_table.z = elec_xyz(elecInx,3);
electrode_table.type = elec_types(elecInx);

% Generate output name
electrodes_tsv_name = fullfile(dataWriteDir, sprintf('sub-%s_ses-%s_electrodes.tsv', sub_label, ses_label));

% Write tsv file
writetable(electrode_table,electrodes_tsv_name,'FileType','text','Delimiter','\t');

%% Create RUN-SPECIFIC files %%%%%%%%%%%%%%%%%%

% It generates:
%   - events.tsv
%   - ieeg.edf 
%   - .mat with stimulus info per run (goes in main 'stimuli' folder)
%   - ieeg.json 
%   - channels.tsv TO DO

%% Big loop across runs

% This loop:
%   - extracts run-specific stimulus information from stimulus files
%   - matches stimuli to trigger onsets
%   - splits data up in separate runs
%   - writes out all the run specific files required for BIDS

num_trials_total = 0;

for ii = 1:length(stimData)
    
    stim0 = num_trials_total+1;
    
    % Generate filename
    fname = sprintf('sub-%s_ses-%s_task-%s_run-%s', ...
            sub_label, ses_label, task_label{ii}, run_label{ii});
    fprintf('Creating eeg, tsv, json and channel files for %s \n', fname);
    
    % Generate a json file default
    [ieeg_json, json_options] = createBIDS_ieeg_json_nyuSOM();
    
    if contains(task_label{ii}, 'hrf') %max(taskind_hrf == ii) > 0 % hrf task
                
        % get the timestamps
        blankIdx = mode(stimData(ii).stimulus.seq);
        blanks = stimData(ii).stimulus.seq == blankIdx;
        t0 = stimData(ii).stimulus.seqtiming(find(~blanks,1));
        t_thisrun = stimData(ii).stimulus.seqtiming(~blanks);
        
        num_trials = sum(~blanks);
        
        % task-specific input for tsv file
        duration   = ones(num_trials,1)*0.25;
        ISI        = zeros(num_trials,1);
        trial_type = ones(num_trials,1);
        trial_name = repmat('HRFPATTERN', num_trials, 1);
        stim_file_index = stimData(ii).stimulus.seq(~blanks)';
        
        % task-specific input for json file
        ieeg_json.TaskName = 'bair_hrfpattern';
        ieeg_json.TaskDescription = 'Visual textures presented at irregular intervals';
        ieeg_json.Instructions = 'Detect color change (red/green) at fixation';
        
    else % soc task
        
        % get the timestamps
        t0 = stimData(ii).stimulus.onsets(1);
        t_thisrun = stimData(ii).stimulus.onsets;
        
        num_trials = length(stimData(ii).stimulus.cat);
        
        % task-specific input for tsv file
        duration   = round(stimData(ii).stimulus.duration(stimData(ii).stimulus.cat)',4);
        ISI        = round(stimData(ii).stimulus.ISI(stimData(ii).stimulus.cat)',4);
        trial_type = stimData(ii).stimulus.cat';
        trial_name = stimData(ii).stimulus.categories(stimData(ii).stimulus.cat)';
        stim_file_index = nan(num_trials,1);
        for jj = 1:num_trials
            trial_seq = stimData(ii).stimulus.trial(jj).seq;
            stim_file_index(jj) = trial_seq(1);
        end
        
         % task-specific input for json file
        ieeg_json.TaskName = 'bair_soc';
        ieeg_json.TaskDescription = 'Visual textures, gratings, houses faces and letter presented at various durations and inter-stimulus-intervals';
        ieeg_json.Instructions = 'Detect color change (red/green) at fixation';
        
    end
    
    % Get the onsets
    num_trials_total = num_trials_total + num_trials;
    onsets = trigger_onsets(stim0:num_trials_total);

    % Clip data from run using prescan postscan intervals
    runstart = onsets(1)-prescan; % seconds
    runstop = onsets(end)+postscan; % seconds
    [~,run_start_inx] = intersect(t,runstart); % index
    [~,run_stop_inx] = intersect(t,runstop); % index

    data_thisrun = data(:,run_start_inx:run_stop_inx);
    hdr_thisrun = hdr;
    hdr_thisrun.nSamples = size(data_thisrun,2);

    % Write out new data file
    % EDF format --> has bug?? 
    %data_fname = fullfile(dataWriteDir, sprintf('%s_ieeg.edf', fname));
    %ft_write_data(data_fname, data_thisrun, 'header', hdr_thisrun, 'dataformat', 'edf');
    % BVA format
    data_fname = fullfile(dataWriteDir, sprintf('%s_ieeg', fname));
    ft_write_data(data_fname, data_thisrun, 'header', hdr_thisrun, 'dataformat', 'brainvision_eeg');
    %zip(data_fname, {sprintf('%s.eeg', data_fname), sprintf('%s.vhdr', data_fname), sprintf('%s.vmrk', data_fname)});
    %delete(sprintf('%s.eeg', data_fname), sprintf('%s.vhdr', data_fname), sprintf('%s.vmrk', data_fname));
    
    % Collect info for tsv files
    onset      = round(onsets'-onsets(1)+prescan,3);
    stim_file  = repmat(fname, num_trials, 1);

    % Write out tsv file 
    tsv_thisrun = table(onset, duration, ISI, trial_type, trial_name, stim_file, stim_file_index);
    tsv_fname = fullfile(dataWriteDir, sprintf('%s_events.tsv', fname));
    writetable(tsv_thisrun, tsv_fname, 'FileType','text', 'Delimiter', '\t')
    
    % Write out stimulus file
    stimfile_thisrun = stimData(ii);
    stimfile_fname = fullfile(stimWriteDir, sprintf('%s.mat', fname));
    save(stimfile_fname, '-struct', 'stimfile_thisrun', '-v7.3')
    
    % Collect info for json_ieeg file for this run
    ieeg_json.SamplingFrequency = hdr_thisrun.Fs;
    ieeg_json.RecordingDuration = round(hdr_thisrun.nSamples/hdr_thisrun.Fs,3);
    
    % Write out json_ieeg file for this run
    jsonfile_fname = fullfile(dataWriteDir, sprintf('%s_ieeg.json', fname));    
    jsonwrite(jsonfile_fname,ieeg_json,json_options)
    
    % Write out channels.tsv file for this run
    channels_tsv_fname = fullfile(dataWriteDir, sprintf('%s_channels.tsv', fname));    
    writetable(channel_table,channels_tsv_fname,'FileType','text','Delimiter','\t');
    
%     % CHECK: Are the onsets from the stimulus file and triggers aligned?
%     figure,
%     stem(trigger_onsets(stim0:stim0+num_trials-1)-trigger_onsets(stim0)); 
%     hold on,
%     stem(t_thisrun - t0, ':diamondr')
%     xlabel('Event number'); ylabel('Time (s)');
%     legend('Triggers', 'Stimulus Onsets')
end

% CHECK: Do number of triggers derived from EDF match number
% of trials from stimulus files?
assert(isequal(length(trigger_onsets), num_trials_total))



