function [stimData] = bidsconvert_readstimulusfiles(dataReadDir, patientID, ses_label, run_label, trigger_onsets, makePlots)

if nargin < 6 || isempty(makePlots)
    makePlots = 0;
end
% READ IN relevant data files %%%%%%%%%%%%%%%%%%

%   - stimulus log files generated by stimulus code

stimDir = fullfile(dataReadDir, 'stimdata');
stimMatFiles = dir(fullfile(stimDir, sprintf('sub-*%d*%s*.mat', patientID, ses_label)));
stimTSVFiles = dir(fullfile(stimDir, sprintf('sub-*%d*%s*.tsv', patientID, ses_label)));

% CHECK: Do we have all the stimfiles?
fprintf('[%s] Asserting that we have all the stimFiles \n', mfilename);
assert(isequal(length(stimMatFiles), length(run_label)))
assert(isequal(length(stimTSVFiles), length(run_label)))
nRuns = length(run_label);

% NOTE: It's important to read the StimFiles in in the correct order.
% Because the logfiles are copied over, we can't assume that
% stimFiles(ii).date is correct. Instead, we sort them based on the field
% "experimentDateandTime" in params saved out by the stimulus code.

% Read the stimfiles
clear stimData;
fprintf('[%s] Reading in the following stimFiles: \n', mfilename);
runTimes = [];
for ii = 1:length(stimMatFiles)
    stimData(ii) = load([stimDir filesep stimMatFiles(ii).name]);
    disp(stimData(ii).fname)
    runTimes{ii} = stimData(ii).params.experimentDateandTime;
    if makePlots
        figure(ii); clf
        plot(stimData(ii).stimulus.seqtiming, stimData(ii).stimulus.trigSeq, 'o-')
    end
end

% Sort the stimfiles, count how many triggers were requested
[~, runIndex] = sort(runTimes);
fprintf('[%s] Sorting runs in recorded order. New run order is: \n', mfilename);
stimData_sorted = stimData(runIndex);
requestedTriggerCount = 0;
for ii = 1:length(stimMatFiles)
    disp([stimData_sorted(ii).fname])
    num_triggers = length(find(stimData_sorted(ii).stimulus.trigSeq));
    requestedTriggerCount = requestedTriggerCount+num_triggers;
end

% CHECK: Does the number of requested triggers match the number of triggers
% that were detected in the trigger channel?
fprintf('[%s] Asserting that all the triggers are in the data \n', mfilename);
assert(isequal(requestedTriggerCount, length(trigger_onsets)))
stimData = stimData_sorted;

%read in tsv files later to replace onset with segmented trigger onsets
%readtable([stimDir filesep stimTSVFiles(ii).name], 'FileType');

end